/**
 * Flow Definition Normalizer — Power Automate MCP v3.3.0
 *
 * Auto-fixes common issues in flow definitions generated by AI agents:
 * - Converts snake_case properties to camelCase (run_after → runAfter)
 * - Injects missing $schema and contentVersion
 * - Handles nested action/trigger structures recursively
 *
 * This is a safety net — the workflow-create-flow prompt teaches agents
 * the correct format, but this catches errors when they don't comply.
 *
 * Fixes applied based on production errors:
 *   2026-03-25 Jose Error 1: "Could not find member 'run_after'" → run_after → runAfter
 *   2026-03-25 Jose Error 2: "Required property '$schema' not found" → $schema injection
 *   2026-03-25 Jose Error 3: "Could not find member 'default_value'" → default_value → defaultValue
 */

// Known snake_case → camelCase mappings for Flow definition properties
const DEFINITION_PROPERTY_MAP: Record<string, string> = {
  // Core action properties
  'run_after': 'runAfter',
  'trigger_conditions': 'triggerConditions',
  'operation_id': 'operationId',
  'content_type': 'contentType',
  'relative_path': 'relativePath',
  'retry_policy': 'retryPolicy',
  'operation_options': 'operationOptions',
  'tracked_properties': 'trackedProperties',
  'secure_input': 'secureInput',
  'secure_output': 'secureOutput',
  'split_on': 'splitOn',
  'content_version': 'contentVersion',
  'child_items': 'childItems',
  'table_name': 'tableName',
  'row_id': 'rowId',
  'run_after_status': 'runAfterStatus',
  'include_nested_actions': 'includeNestedActions',

  // Parameter / $connections properties (Jose's Error 3 — 2026-03-25)
  'default_value': 'defaultValue',
  'allowed_values': 'allowedValues',
  'is_required': 'isRequired',
  'display_name': 'displayName',
  'parameter_name': 'parameterName',
  'connection_id': 'connectionId',
  'connection_name': 'connectionName',
  'connection_reference_logical_name': 'connectionReferenceLogicalName',
  'api_id': 'apiId',
};

const REQUIRED_SCHEMA = 'https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#';
const REQUIRED_CONTENT_VERSION = '1.0.0.0';

/**
 * Recursively normalizes snake_case keys to camelCase in flow definitions.
 * Only transforms keys that are in the DEFINITION_PROPERTY_MAP to avoid
 * mangling action names or user-defined strings.
 */
function normalizeKeys(obj: any): any {
  if (obj === null || obj === undefined) return obj;
  if (Array.isArray(obj)) return obj.map(normalizeKeys);
  if (typeof obj !== 'object') return obj;

  const normalized: Record<string, any> = {};
  for (const [key, value] of Object.entries(obj)) {
    const mappedKey = DEFINITION_PROPERTY_MAP[key] || key;
    normalized[mappedKey] = normalizeKeys(value);
  }
  return normalized;
}

/**
 * Normalizes a flow definition for the Power Automate API.
 *
 * Fixes applied:
 * 1. Injects $schema if missing
 * 2. Injects contentVersion if missing
 * 3. Converts snake_case properties → camelCase recursively
 * 4. Logs what was fixed for diagnostics
 *
 * @param definition - Raw definition from agent
 * @returns Normalized definition ready for the Flow API
 */
export function normalizeDefinition(definition: any): any {
  if (!definition || typeof definition !== 'object') return definition;

  const fixes: string[] = [];

  // Step 1: Inject $schema if missing
  if (!definition['$schema']) {
    definition['$schema'] = REQUIRED_SCHEMA;
    fixes.push('injected $schema');
  }

  // Step 2: Inject contentVersion if missing
  if (!definition['contentVersion'] && !definition['content_version']) {
    definition['contentVersion'] = REQUIRED_CONTENT_VERSION;
    fixes.push('injected contentVersion');
  }

  // Step 3: Recursive snake_case → camelCase normalization
  const normalized = normalizeKeys(definition);

  // Step 4: Count and log remapped keys
  const originalStr = JSON.stringify(definition);
  let remappedCount = 0;
  for (const key of Object.keys(DEFINITION_PROPERTY_MAP)) {
    const regex = new RegExp(`"${key}"\\s*:`, 'g');
    const matches = originalStr.match(regex);
    if (matches) remappedCount += matches.length;
  }

  if (fixes.length > 0 || remappedCount > 0) {
    const allFixes = [...fixes];
    if (remappedCount > 0) {
      allFixes.push(`remapped ${remappedCount} snake_case properties (e.g., run_after → runAfter, default_value → defaultValue)`);
    }
    console.log(`[NormalizeDef] Applied ${allFixes.length} fixes: ${allFixes.join(', ')}`);
  }

  return normalized;
}
